site_name: Saltylord Scripts
site_url: https://mydomain.org/mysite

theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
  markdown_extensions:
    - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables
      - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
